### PR TITLE
Updating documentation for HTTPSession - XAP 10.2

### PR DESCRIPTION
**Pull request by yohanakh**

### CODE REVIEW

**Comment by yohanakh** [comment]
I have added new commit to this pull request... Is it okay? should i create  a new pull request? 
I saw that the first commit is already on master but the pull request is not closed.
Thanks

**Comment by croffler** [comment]
Yes I saw that , when I merged and committed your request it did not sow it as closed.

Not sure what happened, need to see whats going on

Chris

On Jul 10, 2015, at 10:17 PM, Yohana Khoury wrote:


I have added new commit to this pull request... Is it okay? should i create a new pull request?
I saw that the first commit is already on master but the pull request is not closed.
Thanks

**Comment by yohanakh** [comment]
Should i create a new pull request ?

**Comment by yohanakh** [comment]
I saw that the build fails because sbp folder is deleted... I will close this pull request and create new one

**Comment by croffler** [comment]
thanks

still do not know what happened

On Jul 13, 2015, at 12:15 PM, Yohana Khoury wrote:


I saw that the build fails because sbp folder is deleted... I will close this pull request and create new one

**Pull request closed without merging**
